### ISSUE TITLE
Can't login after entering wrong password

### ISSUE THREAD

**Issue by bendovercz** [artur9010/lightdm-webkit-material#12]
When I enter a wrong password and log in, nothing happens. No error message, nothing. So I correct my password but now I'm unable to login (no error message shows up). I have to restart X to do so. Is it just me or is it a bug?

**Comment by jebaum** [comment]
This bug is "fixed" by adding

```
else {
   login.init();
}
```

to the `if` statement in `window.authentication_complete()` in `login.js`.

I say "fixed" because the user gets no feedback about the incorrect password, and can continue typing and backspacing if he/she does so immediately after hitting enter, and before the field is automatically cleared. I'd like to clean up this behavior some, then I'll send a PR. But that aside, you can login once you enter the correct password after making the above change.

Actually I should clarify, I don't use this theme, I just use `login.js` for my own theme, so I might not be the best candidate to send a PR.

**Comment by blamejoel** [comment]
any progress on this bug?
